Fix test compile time warnings
A number of tests cause compiler warnings like this:

hashcrypt_speed.c: In function ‘hash_data’:
hashcrypt_speed.c:101:2: warning: implicit declaration of function ‘alarm’ [-Wimplicit-function-declaration]
  alarm(5);
  ^~~~~
hashcrypt_speed.c: In function ‘main’:
hashcrypt_speed.c:203:2: warning: implicit declaration of function ‘close’ [-Wimplicit-function-declaration]
  close(fdc);
  ^~~~~

Fix by including unistd.h.